# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftBaseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftBaseProject
    pod 'KeychainAccess'
    pod 'MBProgressHUD'
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
    pod 'Kingfisher'
end
